language: python
python:
  - "2.7"
script: nosetests xivo-dao
services: postgresql
before_script: 
    - psql -U postgres -c "create database asterisktest;"
    - psql -U postgres -c "create user asterisk with password 'asterisk';"
    - psql -U postgres -c "grant all on database asterisktest to asterisk;"
notifications:
  email:
    recipients:
      - tests-reports@avencall.com
    on_success: change
    on_failure: change
branches:
  only:
    - master
